model: |
  [request_definition]
  r = sub, obj, act
  
  [policy_definition]
  p = sub_rule, obj, act
  
  [policy_effect]
  e = some(where (p.eft == allow))
  
  [matchers]
  m = eval(p.sub_rule) && keyMatch(r.obj, p.obj) && regexMatch(r.act, p.act)

services:
  - name: user-service
    entrypoint: http://user-service:5001/
    inject_token_in_swagger: true

  - name: music-service
    entrypoint: http://music-service:5002/
    inject_token_in_swagger: true

  - name: analytics-service
    entrypoint: http://analytics-service:5003/
    inject_token_in_swagger: true

  - name: recommendation-service
    entrypoint: http://recommendation-service:5004/
    inject_token_in_swagger: true

policies:
  # ---------------- USER-SERVICE ----------------
  - service: user-service
    rule: r.sub.group_id == 3
    resource: /users/*
    methods: GET

  - service: user-service
    rule: r.sub.group_id == 3
    resource: /users/*
    methods: (GET)|(POST)|(PUT)|(DELETE)|(PATCH)

  - service: user-service
    rule: r.sub.group_id == 3
    resource: /groups*
    methods: (GET)|(POST)|(PUT)|(DELETE)|(PATCH)

  # Регистрация и логин разрешены для всех
  - service: user-service
    resource: /auth/*
    methods: POST
    white_list: true

  # Профиль пользователя доступен для авторизованных пользователей
  - service: user-service
    resource: /users/*
    methods: (GET)|(PATCH)
    rule: r.sub.group_id > 0

  # ---------------- MUSIC-SERVICE ----------------
  # Только авторизованные пользователи могут видеть треки
  - service: music-service
    resource: /tracks*
    methods: (GET)
    rule: r.sub.group_id >= 0

  - service: music-service
    resource: /track/random-track
    methods: (GET)
    rule: r.sub.group_id >= 0

  - service: music-service
    resource: /tracks/search
    methods: (GET)
    rule: r.sub.group_id >= 0

  # Только авторизованные могут загружать/удалять треки
  - service: music-service
    resource: /tracks/upload
    methods: POST
    rule: r.sub.group_id > 0

  - service: music-service
    resource: /tracks/*
    methods: (PUT)|(DELETE)
    rule: r.sub.group_id > 0

  - service: music-service
    resource: /files*
    methods: (GET)|(POST)|(DELETE)
    rule: r.sub.group_id > 0

  # ---------------- PLAYLISTS ----------------
  # Авторизованные пользователи могут создавать плейлисты с обложкой
  - service: music-service
    resource: /playlists/with-cover
    methods: POST
    rule: r.sub.group_id > 0

  # Авторизованные пользователи могут обновлять обложку плейлиста
  - service: music-service
    resource: /playlists/cover/*
    methods: PUT
    rule: r.sub.group_id > 0

  # Авторизованные пользователи могут редактировать свои плейлисты
  - service: music-service
    resource: /playlists/*
    methods: PUT
    rule: r.sub.group_id > 0

  # Авторизованные пользователи могут удалять свои плейлисты
  - service: music-service
    resource: /playlists/*
    methods: DELETE
    rule: r.sub.group_id > 0

  # Просмотр всех пользовательских плейлистов
  - service: music-service
    resource: /playlists
    methods: GET
    rule: r.sub.group_id > 0

  # Просмотр публичных плейлистов
  - service: music-service
    resource: /playlists/public
    methods: GET
    rule: r.sub.group_id > -1

  # Просмотр конкретного плейлиста
  - service: music-service
    resource: /playlists/*
    methods: GET
    rule: r.sub.group_id > 0

  # Добавление трека в плейлист
  - service: music-service
    resource: /playlists/*
    methods: POST
    rule: r.sub.group_id > 0

  # Удаление трека из плейлиста
  - service: music-service
    resource: /playlists/*
    methods: DELETE
    rule: r.sub.group_id > 0

  # ---------------- FAVORITES ----------------
  # Только авторизованные пользователи могут добавлять/удалять треки в избранное
  - service: music-service
    resource: /favorites/*
    methods: POST
    rule: r.sub.group_id > 0

  - service: music-service
    resource: /favorites*
    methods: GET
    rule: r.sub.group_id > 0

  - service: music-service
    resource: /favorites/*
    methods: DELETE
    rule: r.sub.group_id > 0

  # ---------------- HISTORY ----------------

  - service: music-service
    resource: /history*
    methods: GET
    rule: r.sub.group_id > 0

  - service: music-service
    resource: /history/*
    methods: POST
    rule: r.sub.group_id > 0


  # ---------------- ANALYTICS ----------------

  - service: analytics-service
    resource: /user/analytics/raw-data*
    methods: GET
    rule: r.sub.group_id > 0

  - service: analytics-service
    resource: /user/analytics/*
    methods: GET
    rule: r.sub.group_id > 0

  - service: analytics-service
    resource: /user/analytics/*
    methods: PUT
    rule: r.sub.group_id > 0

  # ---------------- RECOMMENDATION ----------------

  - service: recommendation-service
    resource: /my-wave*
    methods: GET
    rule: r.sub.group_id > 0

  - service: recommendation-service
    resource: /recommendations/*
    methods: GET
    rule: r.sub.group_id > 0
